import streamlit as st
from PIL import Image, ImageDraw, ImageFont
import io
import os
 
# --- Configuration ---
st.set_page_config(
    page_title="Image Watermarker",
    layout="centered",
    initial_sidebar_state="auto"
)
 
# --- Watermarking Function ---
def add_watermark(image_file, watermark_text, opacity):
    """Adds a semi-transparent text watermark to an image."""
    try:
        # Open the image file and convert to RGBA (to support transparency)
        img = Image.open(image_file).convert("RGBA")
        width, height = img.size
 
        # Create a blank, transparent overlay layer
        overlay = Image.new('RGBA', img.size, (255, 255, 255, 0))
        draw = ImageDraw.Draw(overlay)
 
        # 1. Define Font and Size
        # Calculate font size based on image height (e.g., 5% of height)
        font_size = max(20, int(height * 0.05))
       
        # Try to use a common font, fall back to default if not found
        try:
            # Using Arial/Inter is common, but it depends on the host system.
            # We'll try a common font and then fall back to the PIL default.
            font = ImageFont.truetype("arial.ttf", font_size)
        except IOError:
            font = ImageFont.load_default()
            font_size = 50 # Increase size if using default font which is very small
 
        # 2. Define Position (Bottom Right Corner)
        bbox = draw.textbbox((0, 0), watermark_text, font=font)
        text_width = bbox[2] - bbox[0]
        text_height = bbox[3] - bbox[1]
 
        margin = int(width * 0.02) # 2% margin
        x = width - text_width - margin
        y = height - text_height - margin
 
        # 3. Define Color and Opacity (Alpha Channel)
        # Alpha is calculated from the 0-100 slider value to a 0-255 scale
        alpha = int(255 * (opacity / 100))
        # White text, with calculated transparency
        fill_color = (255, 255, 255, alpha)
 
        # Draw the text on the transparent overlay
        draw.text((x, y), watermark_text, font=font, fill=fill_color)
 
        # Combine the original image and the watermark overlay
        watermarked_img = Image.alpha_composite(img, overlay)
 
        # Convert back to RGB for standard saving/display (e.g., as JPEG/PNG)
        return watermarked_img.convert("RGB")
 
    except Exception as e:
        st.error(f"An error occurred during watermarking: {e}")
        return None
 
# --- Main Streamlit App ---
 
st.title("🛡️ Simple Image Watermarker")
st.markdown("Upload your image, add your watermark text, and set the opacity.")
 
# 1. Inputs
uploaded_file = st.file_uploader(
    "Choose an Image File (JPG, PNG)",
    type=["jpg", "jpeg", "png"]
)
 
watermark_text = st.text_input(
    "Watermark Text (e.g., '© MyPhotoGallery')",
    value="© Generated by Gemini",
    max_chars=50
)
 
opacity = st.slider(
    "Watermark Opacity (%)",
    min_value=10,
    max_value=100,
    value=50,
    step=5
)
 
if uploaded_file is not None and watermark_text:
    # --- Processing ---
    st.subheader("Processing Image...")
   
    # Generate the watermarked image
    final_image = add_watermark(uploaded_file, watermark_text, opacity)
 
    if final_image:
        st.subheader("✅ Watermarked Image Preview")
       
        # Display the image in the Streamlit app
        st.image(final_image, caption="Watermarked Result", use_column_width=True)
 
        # --- Download Logic ---
        # Save the watermarked image to a buffer (in-memory)
        buffer = io.BytesIO()
        # Determine the correct format from the original upload
        file_extension = uploaded_file.name.split('.')[-1].upper()
       
        # PNG supports better quality, use it for saving if original was PNG
        save_format = 'PNG' if file_extension == 'PNG' else 'JPEG'
       
        # Save to buffer
        final_image.save(buffer, format=save_format)
       
        # Provide the download button
        download_filename = f"watermarked_image.{save_format.lower()}"
       
        st.download_button(
            label=f"⬇️ Download Watermarked {save_format} File",
            data=buffer.getvalue(),
            file_name=download_filename,
            mime=f"image/{save_format.lower()}",
            help="Click to download your image with the watermark applied."
        )
 
elif uploaded_file is None:
    st.info("Please upload an image file to begin.")
   
elif not watermark_text:
    st.warning("Please enter some text for the watermark.")
